import React from 'react';
import JoinScreen from '../../screens/JoinScreen';
import GameSelectionScreen from '../../screens/GameSelectionScreen';
import LobbyScreen from '../../screens/LobbyScreen';

// Lazy-loaded game screens
import CustomQuestionsScreen from '../../screens/CustomQuestionsScreen';
import QuestionScreen from '../../screens/QuestionScreen';
import ResultsScreen from '../../screens/ResultsScreen';
import MythOrFactQuestionScreen from '../../screens/MythOrFactQuestionScreen';
import MythOrFactResultsScreen from '../../screens/MythOrFactResultsScreen';
import WhosMostLikelyQuestionScreen from '../../screens/WhosMostLikelyQuestionScreen';
import WhosMostLikelyResultsScreen from '../../screens/WhosMostLikelyResultsScreen';
import NeonTapGameScreen from '../../screens/NeonTapGameScreen';
import NeonTapResultsScreen from '../../screens/NeonTapResultsScreen';
import WordRushGameScreen from '../../screens/WordRushGameScreen';
import WordRushResultsScreen from '../../screens/WordRushResultsScreen';
import WordRushWinnerScreen from '../../screens/WordRushWinnerScreen';
import TruthOrDareCategorySelectionScreen from '../../screens/TruthOrDareCategorySelectionScreen';
import TruthOrDareGameScreen from '../../screens/TruthOrDareGameScreen';
import OnlineTruthOrDareCategoryScreen from '../../screens/OnlineTruthOrDareCategoryScreen';
import OnlineTruthOrDareGameScreen from '../../screens/OnlineTruthOrDareGameScreen';
import WouldYouRatherScreen from '../../screens/WouldYouRatherScreen';
import SpinTheBottleScreen from '../../screens/SpinTheBottleScreen';
import WhotGameScreen from '../../screens/WhotGameScreen';
import ScoreboardScreen from '../../screens/ScoreboardScreen';
import NeverHaveIEverCategoryScreen from '../../screens/NeverHaveIEverCategoryScreen';
import NeverHaveIEverScreen from '../../screens/NeverHaveIEverScreen';
import OnlineNHIECategoryScreen from '../../screens/OnlineNHIECategoryScreen';
import OnlineNeverHaveIEverScreen from '../../screens/OnlineNeverHaveIEverScreen';
import ScrabbleScreen from '../../screens/ScrabbleScreen';
import OnlineScrabbleScreen from '../../screens/OnlineScrabbleScreen';
import ScrabbleDifficultyScreen from '../../screens/ScrabbleDifficultyScreen';
import MVPVotingScreen from '../../screens/MVPVotingScreen';
import TeamSetupScreen from '../../screens/TeamSetupScreen';
import PlaylistSetupScreen from '../../screens/PlaylistSetupScreen';
import CaptionThisScreen from '../../screens/CaptionThisScreen';
import SpeedCategoriesScreen from '../../screens/SpeedCategoriesScreen';
import AuctionBluffScreen from '../../screens/AuctionBluffScreen';
import MemoryChainScreen from '../../screens/MemoryChainScreen';
import SpectatorScreen from '../../screens/SpectatorScreen';
import JoinSpectatorScreen from '../../screens/JoinSpectatorScreen';
import ConfessionRouletteScreen from '../../screens/ConfessionRouletteScreen';
import ImposterScreen from '../../screens/ImposterScreen';
import UnpopularOpinionsScreen from '../../screens/UnpopularOpinionsScreen';
import TicTacToeDifficultyScreen from '../../screens/TicTacToeDifficultyScreen';
import SpillTheTeaScreen from '../../screens/SpillTheTeaScreen';
import HotSeatScreen from '../../screens/HotSeatScreen';
import HotSeatCategoryScreen from '../../screens/HotSeatCategoryScreen';
import HotSeatMCScreen from '../../screens/HotSeatMCScreen';
import ButtonMashScreen from '../../screens/ButtonMashScreen';
import TypeRaceScreen from '../../screens/TypeRaceScreen';
import MathBlitzScreen from '../../screens/MathBlitzScreen';
import ColorRushScreen from '../../screens/ColorRushScreen';
import MemoryMatchScreen from '../../screens/MemoryMatchScreen';
import TicTacToeScreen from '../../screens/TicTacToeScreen';
import DrawBattleScreen from '../../screens/DrawBattleScreen';
import LieDetectorScreen from '../../screens/LieDetectorScreen';
import RealTalkCategoryScreen from '../../screens/RealTalkCategoryScreen';
import RealTalkScreen from '../../screens/RealTalkScreen';
import OnlineRealTalkCategoryScreen from '../../screens/OnlineRealTalkCategoryScreen';
import OnlineRealTalkScreen from '../../screens/OnlineRealTalkScreen';

export const OnlinePlayGroup = (Stack) => (
    <Stack.Group>
        <Stack.Screen name="Join" component={JoinScreen} />
        <Stack.Screen name="GameSelection" component={GameSelectionScreen} />
        <Stack.Screen name="Lobby" component={LobbyScreen} />
        <Stack.Screen name="CustomQuestions" component={CustomQuestionsScreen} />
        <Stack.Screen name="Question" component={QuestionScreen} />
        <Stack.Screen name="Results" component={ResultsScreen} />
        <Stack.Screen name="MythOrFactQuestion" component={MythOrFactQuestionScreen} />
        <Stack.Screen name="MythOrFactResults" component={MythOrFactResultsScreen} />
        <Stack.Screen name="WhosMostLikelyQuestion" component={WhosMostLikelyQuestionScreen} />
        <Stack.Screen name="WhosMostLikelyResults" component={WhosMostLikelyResultsScreen} />
        <Stack.Screen name="NeonTapGame" component={NeonTapGameScreen} />
        <Stack.Screen name="NeonTapResults" component={NeonTapResultsScreen} />
        <Stack.Screen name="WordRushGame" component={WordRushGameScreen} />
        <Stack.Screen name="WordRushResults" component={WordRushResultsScreen} />
        <Stack.Screen name="WordRushWinner" component={WordRushWinnerScreen} />
        <Stack.Screen name="TruthOrDareCategorySelection" component={TruthOrDareCategorySelectionScreen} />
        <Stack.Screen name="TruthOrDareGame" component={TruthOrDareGameScreen} />
        <Stack.Screen name="OnlineTruthOrDareCategory" component={OnlineTruthOrDareCategoryScreen} />
        <Stack.Screen name="OnlineTruthOrDareGame" component={OnlineTruthOrDareGameScreen} />
        <Stack.Screen name="WouldYouRather" component={WouldYouRatherScreen} />
        <Stack.Screen name="SpinTheBottle" component={SpinTheBottleScreen} />
        <Stack.Screen name="WhotGame" component={WhotGameScreen} />
        <Stack.Screen name="Scoreboard" component={ScoreboardScreen} />
        <Stack.Screen name="NeverHaveIEverCategory" component={NeverHaveIEverCategoryScreen} />
        <Stack.Screen name="NeverHaveIEver" component={NeverHaveIEverScreen} />
        <Stack.Screen name="OnlineNHIECategory" component={OnlineNHIECategoryScreen} />
        <Stack.Screen name="OnlineNeverHaveIEver" component={OnlineNeverHaveIEverScreen} />
        <Stack.Screen name="Scrabble" component={ScrabbleScreen} />
        <Stack.Screen name="OnlineScrabble" component={OnlineScrabbleScreen} />
        <Stack.Screen name="ScrabbleDifficulty" component={ScrabbleDifficultyScreen} />
        <Stack.Screen name="ScrabbleAI" component={ScrabbleScreen} />
        <Stack.Screen name="MVPVoting" component={MVPVotingScreen} />
        <Stack.Screen name="TeamSetup" component={TeamSetupScreen} />
        <Stack.Screen name="PlaylistSetup" component={PlaylistSetupScreen} />
        <Stack.Screen name="CaptionThis" component={CaptionThisScreen} />
        <Stack.Screen name="SpeedCategories" component={SpeedCategoriesScreen} />
        <Stack.Screen name="AuctionBluff" component={AuctionBluffScreen} />
        <Stack.Screen name="MemoryChain" component={MemoryChainScreen} />
        <Stack.Screen name="Spectator" component={SpectatorScreen} />
        <Stack.Screen name="JoinSpectator" component={JoinSpectatorScreen} />
        <Stack.Screen name="ConfessionRoulette" component={ConfessionRouletteScreen} />
        <Stack.Screen name="Imposter" component={ImposterScreen} />
        <Stack.Screen name="UnpopularOpinions" component={UnpopularOpinionsScreen} />
        <Stack.Screen name="TicTacToeDifficulty" component={TicTacToeDifficultyScreen} />
        <Stack.Screen name="SpillTheTea" component={SpillTheTeaScreen} />
        <Stack.Screen name="HotSeat" component={HotSeatScreen} />
        <Stack.Screen name="HotSeatCategory" component={HotSeatCategoryScreen} />
        <Stack.Screen name="HotSeatMC" component={HotSeatMCScreen} />
        <Stack.Screen name="ButtonMash" component={ButtonMashScreen} />
        <Stack.Screen name="TypeRace" component={TypeRaceScreen} />
        <Stack.Screen name="MathBlitz" component={MathBlitzScreen} />
        <Stack.Screen name="ColorRush" component={ColorRushScreen} />
        <Stack.Screen name="MemoryMatch" component={MemoryMatchScreen} />
        <Stack.Screen name="TicTacToe" component={TicTacToeScreen} />
        <Stack.Screen name="DrawBattle" component={DrawBattleScreen} />
        <Stack.Screen name="LieDetector" component={LieDetectorScreen} />
        <Stack.Screen name="RealTalkCategory" component={RealTalkCategoryScreen} />
        <Stack.Screen name="RealTalk" component={RealTalkScreen} />
        <Stack.Screen name="OnlineRealTalkCategory" component={OnlineRealTalkCategoryScreen} />
        <Stack.Screen name="OnlineRealTalk" component={OnlineRealTalkScreen} />
    </Stack.Group>
);
